"""Regression test file generator.

After a scan, if any variants evaded detection this module produces a pytest
file with one test function per evasion.  Each test asserts that dlpscan's
InputGuard detects the obfuscated variant — tests will fail until the scanner
is updated to close the gap.
"""
from __future__ import annotations

import re
from collections import defaultdict

from evadex.core.result import PayloadCategory, ScanResult, SeverityLevel


_CATEGORY_PRESET: dict[PayloadCategory, str] = {
    PayloadCategory.CREDIT_CARD: "Preset.PCI_DSS",
    PayloadCategory.IBAN:        "Preset.PCI_DSS",
    PayloadCategory.SWIFT_BIC:   "Preset.PCI_DSS",
    PayloadCategory.ABA_ROUTING: "Preset.PCI_DSS",
    PayloadCategory.BITCOIN:     "Preset.PCI_DSS",
    PayloadCategory.ETHEREUM:    "Preset.PCI_DSS",
    PayloadCategory.SSN:          "Preset.PII",
    PayloadCategory.SIN:          "Preset.PII",
    PayloadCategory.EMAIL:        "Preset.PII",
    PayloadCategory.PHONE:        "Preset.PII",
    PayloadCategory.US_PASSPORT:  "Preset.PII",
    PayloadCategory.AU_TFN:       "Preset.PII",
    PayloadCategory.DE_TAX_ID:    "Preset.PII",
    PayloadCategory.FR_INSEE:     "Preset.PII",
    PayloadCategory.AWS_KEY:        "Preset.CREDENTIALS",
    PayloadCategory.JWT:            "Preset.CREDENTIALS",
    PayloadCategory.GITHUB_TOKEN:   "Preset.CREDENTIALS",
    PayloadCategory.STRIPE_KEY:     "Preset.CREDENTIALS",
    PayloadCategory.SLACK_TOKEN:    "Preset.CREDENTIALS",
    PayloadCategory.CLASSIFICATION: "Preset.CREDENTIALS",
}
_DEFAULT_PRESET = "Preset.PCI_DSS"


def _slug(text: str) -> str:
    """Convert a label or technique name to a safe Python identifier fragment."""
    text = text.lower()
    text = re.sub(r"[^a-z0-9]+", "_", text)
    return text.strip("_")


def generate_regression_code(results: list[ScanResult]) -> str:
    """Return Python source for a pytest regression file from evasion results.

    Returns an empty string if there are no evasions.
    """
    evasions = [r for r in results if r.severity == SeverityLevel.FAIL]
    if not evasions:
        return ""

    seen_counts: defaultdict[str, int] = defaultdict(int)
    blocks: list[str] = []

    for result in evasions:
        label_slug = _slug(result.payload.label)
        tech_slug  = _slug(result.variant.technique)
        base_name  = f"test_{label_slug}_{tech_slug}"

        seen_counts[base_name] += 1
        count = seen_counts[base_name]
        func_name = base_name if count == 1 else f"{base_name}_{count}"

        preset       = _CATEGORY_PRESET.get(result.payload.category, _DEFAULT_PRESET)
        variant_repr = repr(result.variant.value)
        comment      = f"  # {result.variant.transform_name}"

        block = (
            f"def {func_name}():\n"
            f"    \"\"\"{result.payload.label} evaded via {result.variant.technique}"
            f" \u2014 should be detected\"\"\"\n"
            f"    from dlpscan import InputGuard, Preset\n"
            f"    guard = InputGuard(presets=[{preset}])\n"
            f"    result = guard.scan({variant_repr}){comment}\n"
            f"    assert not result.is_clean\n"
        )
        blocks.append(block)

    header = (
        '"""Regression tests generated by evadex.\n\n'
        "Each test represents an obfuscated variant that evaded detection during the last scan.\n"
        "Run with: pytest evadex_regressions.py\n\n"
        "These tests will FAIL until the scanner is updated to detect each technique.\n"
        '"""\n'
        "import pytest  # noqa: F401\n\n\n"
    )

    return header + "\n\n".join(blocks) + "\n"


def write_regression_file(results: list[ScanResult], path: str) -> None:
    """Write the regression pytest file to *path*.

    Does nothing if there are no evasions in *results*.
    """
    code = generate_regression_code(results)
    if not code:
        return
    with open(path, "w", encoding="utf-8") as f:
        f.write(code)
