"""DOCX writer for evadex generate.

Structure:
  - Title page (document name, date, disclaimer)
  - One heading-1 section per category
    - Prose paragraphs for the first two-thirds of entries
    - A table for the remaining third (shows plain / variant / technique)
"""
from __future__ import annotations

import datetime
from collections import defaultdict

from docx import Document
from docx.shared import RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

from evadex.generate.generator import GeneratedEntry
from evadex.core.result import PayloadCategory


_SECTION_TITLES: dict[PayloadCategory, str] = {
    PayloadCategory.CREDIT_CARD: "Credit Card Numbers",
    PayloadCategory.SSN:         "Social Security Numbers",
    PayloadCategory.SIN:         "Canadian Social Insurance Numbers",
    PayloadCategory.IBAN:        "International Bank Account Numbers",
    PayloadCategory.SWIFT_BIC:   "SWIFT / BIC Codes",
    PayloadCategory.ABA_ROUTING: "ABA Routing Numbers",
    PayloadCategory.BITCOIN:     "Bitcoin Addresses",
    PayloadCategory.ETHEREUM:    "Ethereum Addresses",
    PayloadCategory.US_PASSPORT: "US Passport Numbers",
    PayloadCategory.AU_TFN:      "Australian Tax File Numbers",
    PayloadCategory.DE_TAX_ID:   "German Tax Identification Numbers",
    PayloadCategory.FR_INSEE:    "French INSEE / NIR Numbers",
    PayloadCategory.AWS_KEY:     "AWS Access Keys",
    PayloadCategory.GITHUB_TOKEN:"GitHub Personal Access Tokens",
    PayloadCategory.STRIPE_KEY:  "Stripe API Keys",
    PayloadCategory.SLACK_TOKEN: "Slack Bot Tokens",
    PayloadCategory.JWT:         "JSON Web Tokens",
    PayloadCategory.CLASSIFICATION: "Classification Labels",
    PayloadCategory.EMAIL:       "Email Addresses",
    PayloadCategory.PHONE:       "Phone Numbers",
}


def _shade_cell(cell, hex_color: str) -> None:
    tc = cell._tc
    tcPr = tc.get_or_add_tcPr()
    shd = OxmlElement("w:shd")
    shd.set(qn("w:val"), "clear")
    shd.set(qn("w:color"), "auto")
    shd.set(qn("w:fill"), hex_color)
    tcPr.append(shd)


def _add_table_section(doc: Document, entries: list[GeneratedEntry], cat: PayloadCategory) -> None:
    table = doc.add_table(rows=1, cols=4)
    table.style = "Table Grid"

    hdr_cells = table.rows[0].cells
    for cell, text in zip(hdr_cells, ["#", "Value", "Technique", "Category"]):
        cell.text = text
        cell.paragraphs[0].runs[0].bold = True
        _shade_cell(cell, "1F4E79")
        cell.paragraphs[0].runs[0].font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)

    for i, e in enumerate(entries, 1):
        row = table.add_row().cells
        row[0].text = str(i)
        row[1].text = e.variant_value
        row[2].text = e.technique or "plain"
        row[3].text = cat.value
        if e.technique:
            _shade_cell(row[1], "FFF2CC")

    doc.add_paragraph()


def write_docx(entries: list[GeneratedEntry], path: str) -> None:
    from evadex.generate.writers import (
        _active_template, _active_noise_level, _active_density, _active_seed,
    )

    doc = Document()

    # ── Cover / title ──────────────────────────────────────────────────────
    heading = doc.add_heading("DLP Test Document", 0)
    heading.alignment = WD_ALIGN_PARAGRAPH.CENTER

    today = datetime.date.today().isoformat()
    sub = doc.add_paragraph(f"Generated: {today}")
    sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
    sub.runs[0].italic = True

    disclaimer = doc.add_paragraph(
        "CONFIDENTIAL — This document contains synthetic sensitive data "
        "generated by evadex for DLP scanner testing. "
        "All values are artificial and must not be used in production."
    )
    disclaimer.runs[0].font.color.rgb = RGBColor(0xC0, 0x00, 0x00)
    doc.add_paragraph()

    # If a non-generic template is active, use the template system for content
    if _active_template != "generic":
        from evadex.generate.templates import apply_template
        lines = apply_template(
            _active_template, entries,
            seed=_active_seed,
            noise_level=_active_noise_level,
            density=_active_density,
        )
        for line in lines:
            if line.startswith("===") or line.startswith("---"):
                continue
            if line.strip():
                doc.add_paragraph(line)
        doc.save(path)
        return

    by_cat: dict[PayloadCategory, list[GeneratedEntry]] = defaultdict(list)
    for e in entries:
        by_cat[e.category].append(e)

    for cat in sorted(by_cat.keys(), key=lambda c: c.value):
        cat_entries = by_cat[cat]
        title = _SECTION_TITLES.get(cat, cat.value.replace("_", " ").title())
        doc.add_heading(title, level=1)

        # Split: first ~2/3 as prose, remaining as table
        split = max(1, len(cat_entries) * 2 // 3)
        prose_entries = cat_entries[:split]
        table_entries = cat_entries[split:]

        for e in prose_entries:
            doc.add_paragraph(e.embedded_text)

        if table_entries:
            _add_table_section(doc, table_entries, cat)

    doc.save(path)
