"""PDF writer for evadex generate.

Uses fpdf2 with built-in Helvetica (Latin-1) font.  Variant values that
contain characters outside Latin-1 (e.g. Cyrillic homoglyphs, zero-width
characters) are stored in their original form in the FPDF cell via the
`errors='replace'` codec path — the DLP scanner reads the raw PDF bytes,
which do preserve the original Unicode codepoints in the XML/stream.

For full Unicode rendering fidelity use the XLSX, DOCX, or TXT formats.
"""
from __future__ import annotations

import datetime
from collections import defaultdict

from fpdf import FPDF

from evadex.generate.generator import GeneratedEntry
from evadex.core.result import PayloadCategory


_SECTION_TITLES: dict[PayloadCategory, str] = {
    PayloadCategory.CREDIT_CARD: "Credit Card Numbers",
    PayloadCategory.SSN:         "Social Security Numbers",
    PayloadCategory.SIN:         "Canadian Social Insurance Numbers",
    PayloadCategory.IBAN:        "International Bank Account Numbers",
    PayloadCategory.SWIFT_BIC:   "SWIFT / BIC Codes",
    PayloadCategory.ABA_ROUTING: "ABA Routing Numbers",
    PayloadCategory.BITCOIN:     "Bitcoin Addresses",
    PayloadCategory.ETHEREUM:    "Ethereum Addresses",
    PayloadCategory.US_PASSPORT: "US Passport Numbers",
    PayloadCategory.AU_TFN:      "Australian Tax File Numbers",
    PayloadCategory.DE_TAX_ID:   "German Tax Identification Numbers",
    PayloadCategory.FR_INSEE:    "French INSEE / NIR Numbers",
    PayloadCategory.AWS_KEY:     "AWS Access Keys",
    PayloadCategory.GITHUB_TOKEN:"GitHub Personal Access Tokens",
    PayloadCategory.STRIPE_KEY:  "Stripe API Keys",
    PayloadCategory.SLACK_TOKEN: "Slack Bot Tokens",
    PayloadCategory.JWT:         "JSON Web Tokens",
    PayloadCategory.CLASSIFICATION: "Classification Labels",
    PayloadCategory.EMAIL:       "Email Addresses",
    PayloadCategory.PHONE:       "Phone Numbers",
}


def _safe(text: str) -> str:
    """Map common non-Latin-1 punctuation to ASCII equivalents, then encode to
    Latin-1 to stay within the built-in Helvetica font range."""
    text = (
        text
        .replace("\u2014", "--")   # em-dash
        .replace("\u2013", "-")    # en-dash
        .replace("\u2018", "'")    # left single quotation mark
        .replace("\u2019", "'")    # right single quotation mark / apostrophe
        .replace("\u201c", '"')    # left double quotation mark
        .replace("\u201d", '"')    # right double quotation mark
        .replace("\u2500", "-")    # box-drawing horizontal line (used in txt headers)
        .replace("\u2026", "...")  # ellipsis
    )
    return text.encode("latin-1", errors="replace").decode("latin-1")


class _DlpPDF(FPDF):
    def header(self) -> None:
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 6, "CONFIDENTIAL - DLP Test Document - evadex", align="C", new_x="LMARGIN", new_y="NEXT")
        self.ln(2)

    def footer(self) -> None:
        self.set_y(-12)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 6, f"Page {self.page_no()}", align="C")


def write_pdf(entries: list[GeneratedEntry], path: str) -> None:
    pdf = _DlpPDF()
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.set_margins(18, 18, 18)
    pdf.add_page()

    today = datetime.date.today().isoformat()

    # ── Title block ────────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(31, 78, 121)
    pdf.cell(0, 10, "DLP Test Document", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 6, f"Generated by evadex  |  {today}", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(180, 0, 0)
    pdf.multi_cell(
        0, 5,
        "CONFIDENTIAL - Synthetic data for DLP scanner testing only. "
        "All values are artificial.",
        align="C",
    )
    pdf.ln(8)
    pdf.set_text_color(0, 0, 0)

    # ── Stats block ────────────────────────────────────────────────────────
    by_cat: dict[PayloadCategory, list[GeneratedEntry]] = defaultdict(list)
    for e in entries:
        by_cat[e.category].append(e)

    evasion_count = sum(1 for e in entries if e.technique)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 5,
             f"Total entries: {len(entries)}   |   "
             f"Evasion variants: {evasion_count}   |   "
             f"Plain values: {len(entries) - evasion_count}",
             new_x="LMARGIN", new_y="NEXT")
    pdf.ln(10)
    pdf.set_text_color(0, 0, 0)

    # ── Sections ───────────────────────────────────────────────────────────
    for cat in sorted(by_cat.keys(), key=lambda c: c.value):
        cat_entries = by_cat[cat]
        section_title = _SECTION_TITLES.get(cat, cat.value.replace("_", " ").title())

        # Section heading
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_fill_color(31, 78, 121)
        pdf.set_text_color(255, 255, 255)
        pdf.cell(0, 7, f"  {_safe(section_title)}", fill=True, new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)
        pdf.set_text_color(0, 0, 0)

        pdf.set_font("Helvetica", "", 9)
        for e in cat_entries:
            # Highlight evasion rows with a light yellow background
            if e.technique:
                pdf.set_fill_color(255, 242, 204)
                fill = True
            else:
                fill = False

            text = _safe(e.embedded_text)
            pdf.multi_cell(0, 5, f"  {text}", fill=fill, new_x="LMARGIN", new_y="NEXT")

        pdf.ln(6)

    pdf.output(path)
