"""evadex quickstart — interactive first-time setup wizard."""
from __future__ import annotations

import shutil
import sys
from pathlib import Path

import click
from rich.console import Console

console = Console(stderr=True)


def _detect_evadex_version() -> str:
    try:
        from importlib.metadata import version
        return version("evadex")
    except Exception:
        return "unknown"


def _detect_python_version() -> str:
    return f"{sys.version_info.major}.{sys.version_info.minor}"


def _probe_scanner() -> tuple[str | None, str | None]:
    """Return (tool, exe_path) for the first DLP scanner found on PATH or common locations."""
    for name in ["siphon", "siphon.exe"]:
        p = shutil.which(name)
        if p:
            return "siphon-cli", p
    for name in ["dlpscan", "dlpscan-rs", "dlpscan.exe"]:
        p = shutil.which(name)
        if p:
            return "dlpscan-cli", p
    # Cargo install default
    _sfx = ".exe" if sys.platform == "win32" else ""
    _cargo = Path.home() / ".cargo" / "bin" / f"siphon{_sfx}"
    if _cargo.exists():
        return "siphon-cli", str(_cargo)
    return None, None


def _write_config(tool: str, exe: str | None) -> Path:
    cfg = Path("evadex.yaml")
    lines = ["# evadex config — generated by evadex quickstart", f"tool: {tool}"]
    if exe:
        lines.append(f"exe: {exe}")
    lines += ["tier: banking", "concurrency: 20", ""]
    cfg.write_text("\n".join(lines), encoding="utf-8")
    return cfg


@click.command("quickstart")
def quickstart() -> None:
    """Interactive wizard for first-time evadex setup.

    \b
    Walks through environment detection, scanner setup, and a first test run.
    Saves scanner config to evadex.yaml so subsequent runs just work.

    \b
    Examples:
      evadex quickstart
    """
    # ── Step 1: welcome + environment detection ────────────────────────────────
    console.print()
    console.print("[bold green]Welcome to evadex[/bold green] — DLP quality assurance testing")
    console.print()
    console.print("Checking your environment...")

    evadex_ver = _detect_evadex_version()
    py_ver = _detect_python_version()
    auto_tool, auto_exe = _probe_scanner()

    console.print(f"  [green]✓[/green] evadex {evadex_ver}")
    console.print(f"  [green]✓[/green] Python {py_ver}")
    if auto_exe:
        _label = "Siphon" if "siphon" in (auto_tool or "") else "DLP scanner"
        console.print(f"  [green]✓[/green] {_label} detected at {auto_exe}")
    else:
        console.print("  [red]✗[/red] No DLP scanner found")

    # ── Step 2: scanner selection ──────────────────────────────────────────────
    console.print()
    console.print("Which scanner are you using?")
    console.print("  [bold]1.[/bold] Siphon (recommended)")
    console.print("  [bold]2.[/bold] Other CLI scanner")
    console.print("  [bold]3.[/bold] Skip for now")
    console.print()
    _default_choice = "1" if auto_exe else "3"
    raw = click.prompt("  Choice", default=_default_choice)
    try:
        choice = int(raw.strip())
    except ValueError:
        choice = 3

    tool: str
    exe: str | None

    if choice == 1:
        # ── Step 2a: Siphon path ───────────────────────────────────────────────
        console.print()
        console.print("Where is your Siphon binary?")
        if auto_exe and "siphon" in (auto_tool or ""):
            console.print(
                f"  [dim]auto-detected: {auto_exe}[/dim]  "
                "Press Enter to confirm or type a path:"
            )
            entered = click.prompt("  Path", default=auto_exe)
        else:
            console.print("  Enter the full path to the siphon binary:")
            entered = click.prompt("  Path", default="")
        exe = entered.strip() or None
        tool = "siphon-cli"

    elif choice == 2:
        console.print()
        _dflt = auto_exe or ""
        entered = click.prompt("  Path to scanner executable", default=_dflt)
        exe = entered.strip() or None
        tool = "dlpscan-cli"

    else:
        console.print()
        console.print("[yellow]Skipping scanner setup.[/yellow]")
        console.print()
        console.print(
            "Run [bold]evadex quickstart[/bold] again once you have a scanner installed,\n"
            "or run [bold]evadex init[/bold] to create a config template."
        )
        return

    # ── Step 3: first scan ─────────────────────────────────────────────────────
    console.print()
    console.print("What would you like to test?")
    console.print("  [bold]1.[/bold] Quick check (banking tier, ~4 min with --fast)")
    console.print("  [bold]2.[/bold] Full banking scan (~8 min)")
    console.print("  [bold]3.[/bold] Just generate test files")
    console.print()
    raw_scan = click.prompt("  Choice", default="1")
    try:
        scan_choice = int(raw_scan.strip())
    except ValueError:
        scan_choice = 1

    # Save config now so the scan can pick it up
    cfg_path = _write_config(tool, exe)
    console.print()
    console.print(f"[dim]Scanner config saved to {cfg_path}[/dim]")

    results_dir = Path.home() / ".evadex" / "results"
    results_dir.mkdir(parents=True, exist_ok=True)

    from evadex.cli.app import main as _main
    from click.testing import CliRunner
    runner = CliRunner(mix_stderr=False)

    if scan_choice == 3:
        out_xlsx = results_dir / "test_data.xlsx"
        console.print()
        console.print("Generating test files...")
        r = runner.invoke(_main, [
            "generate", "--format", "xlsx", "--tier", "banking",
            "--count", "100", "--seed", "42",
            "--output", str(out_xlsx),
        ])
        if r.exit_code == 0:
            console.print(f"[green]✓[/green] Test files written to {out_xlsx}")
        else:
            console.print("[red]✗[/red] Generate failed — run [bold]evadex doctor[/bold] to diagnose.")
        console.print()
        console.print("Run [bold]evadex --help[/bold] to see all commands.")
        return

    # Run the scan
    fast = scan_choice == 1
    mode_label = "quick check (--fast)" if fast else "full banking scan"
    console.print()
    console.print(f"Running {mode_label}...")

    output_json = results_dir / "quickstart_scan.json"
    scan_args = [
        "scan",
        "--tool", tool,
        "--tier", "banking",
        "--format", "json",
        "--output", str(output_json),
    ]
    if exe:
        scan_args += ["--exe", exe]
    if fast:
        scan_args += ["--fast"]

    r = runner.invoke(_main, scan_args)

    # ── Step 4: results + next steps ─────────────────────────────────────────
    console.print()
    if r.exit_code != 0:
        console.print("[red]✗[/red] Scan did not complete successfully.")
        console.print("[dim]Run [bold]evadex doctor[/bold] to diagnose environment issues.[/dim]")
        return

    console.print("[green]✓[/green] Scan complete!")
    console.print()

    detection_rate: float | None = None
    try:
        import json as _json
        data = _json.loads(output_json.read_text(encoding="utf-8"))
        meta = data.get("meta", {})
        total = meta.get("total", 0)
        detected = meta.get("detected", 0)
        if total:
            detection_rate = round(detected / total * 100, 1)
    except Exception:
        pass

    if detection_rate is not None:
        console.print(
            f"  Detection rate: [bold]{detection_rate}%[/bold]  —  "
            f"scanner caught {detection_rate} of every 100 test cases"
        )
    console.print(f"  Your results are saved to: [dim]{results_dir}/[/dim]")
    console.print()
    console.print("What next?")
    console.print("  [bold]1.[/bold] Generate test files for your team")
    console.print("  [bold]2.[/bold] View the full report")
    console.print("  [bold]3.[/bold] Run a deeper scan")
    console.print("  [bold]4.[/bold] Exit")
    console.print()
    raw_next = click.prompt("  Choice", default="4")
    try:
        next_choice = int(raw_next.strip())
    except ValueError:
        next_choice = 4

    if next_choice == 1:
        out_xlsx = results_dir / "test_data.xlsx"
        r2 = runner.invoke(_main, [
            "generate", "--format", "xlsx", "--tier", "banking",
            "--count", "100", "--seed", "42",
            "--output", str(out_xlsx),
        ])
        if r2.exit_code == 0:
            console.print(f"[green]✓[/green] Test files written to {out_xlsx}")
        else:
            console.print("[red]✗[/red] Generate failed.")
    elif next_choice == 2:
        report_path = results_dir / "quickstart_report.html"
        r2 = runner.invoke(_main, [
            "report", str(output_json), "--output", str(report_path),
        ])
        if r2.exit_code == 0:
            console.print(f"[green]✓[/green] Report saved to {report_path}")
        else:
            console.print("[red]✗[/red] Report generation failed.")
    elif next_choice == 3:
        console.print()
        console.print("Run: [bold]evadex scan --tier full[/bold] for a comprehensive test")
        console.print("     [bold]evadex scan --tier full --fast[/bold] for a faster comprehensive test")

    console.print()
    console.print("Run [bold]evadex --help[/bold] to see all commands.")
